- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.aria2/aria2.conf:
    ~/.axelrc:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gdbinit:
    ~/.gitconfig:
    ~/.cgdb:
    ~/.gitignore_global:
    ~/.haskeline:
    ~/.hgrc:
    ~/.inputrc:
    ~/.ipython/profile_default/ipython_config.py: ipython/ipython_config.py
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/ipython_kernel_config.py
    ~/.ipython/profile_default/startup/disable_warnings.py: ipython/disable_warnings.py
    ~/.pythonrc:
    ~/.rtorrent.rc:
    ~/.shell:
    ~/.config/tmux: tmux
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vimrc:
    ~/.config/lazygit: lazygit
    # ~/.config/nvim: nvim
    ~/.config/lvim: lvim
    ~/.config/zellij: zellij
    ~/.config/alacritty: alacritty 
    ~/.config/kitty:  kitty
    ~/.vimrc_local:
    ~/.ideavimrc:
    ~/.vsvimrc: vscode/vsvimrc
    ~/.zsh:
    ~/.zshrc:
    ~/Library/Preferences/clangd: clangd  # macos
    ~/.config/clangd: clangd  # macos
    ~/.doom.d: doom.d
    ~/.config/i3: i3
    ~/.config/polybar: polybar
    ~/.config/tmuxinator: tmuxinator
    ~/.config/bspwm: bspwm
    ~/.condarc:
    ~/.proxyrc:
    # ~/.zfunctions/prompt_spaceship_setup: zsh/prompt/spaceship-prompt/spaceship.zsh

- create:
  - ~/.rtorrent/session
  - ~/.rtorrent/watch
  - ~/.rtorrent/downloads

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    shell/plugins/
    zsh/plugins/
