#!/bin/bash

if [[ ! -z $WSL_DISTRO_NAME ]]; then
  hostip=$(cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }')
# wslip=$(hostname -I | awk '{print $1}')
else
  hostip=$(hostname -i)
fi

pxport=7890
 
PROXY_HTTP="http://${hostip}:${pxport}"
PROXY_SOCKS="socks://${hostip}:${pxport}"
 
set_proxy(){
    export http_proxy="${PROXY_HTTP}"
    export HTTP_PROXY="${PROXY_HTTP}"

    export https_proxy="${PROXY_HTTP}"
    export HTTPS_proxy="${PROXY_HTTP}"

    export all_proxy="${PROXY_SOCKS}"
    export ALL_PROXY="${PROXY_SOCKS}"
}

unset_proxy(){
    unset http_proxy
    unset HTTP_PROXY
    unset https_proxy
    unset HTTPS_PROXY
    unset proxy_socks
    unset PROXY_SOCKS
}

test_setting(){
    echo "Host ip:" ${hostip}
    # echo "WSL ip:" ${wslip}
    echo "Current proxy:" $https_proxy
    curl ipinfo.io
}

if [ "$1" = "set" ]
then
    set_proxy
elif [ "$1" = "unset" ]
then
    unset_proxy
elif [ "$1" = "test" ]
then
    test_setting
else
  set_proxy
fi
